inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - db/**/*
    - spec/dummy/db/**/*
    - /**/vendor/**/* # Exclude downloaded gem code in CI
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - spec/**/*

RSpec/BeEql:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: true
  Max: 5

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - spec/**/*
