name: Test supported versions
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_6_1.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0

      - name: Run linters
        run: bundle exec rubocop

  spec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, 3.0]
        gemfile: [rails_5_2, rails_6_0, rails_6_1, rails_7_0]
        exclude:
          - ruby: 2.6
            gemfile: rails_7_0
          - ruby: 3.0
            gemfile: rails_5_2
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: Migrate DB
        run: bundle exec rake app:db:migrate

      - name: Prepare DB
        run: bundle exec rake app:db:test:prepare

      - name: Run spec
        run: bundle exec rspec
